name: xray_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - numpy==1.19.5
    - matplotlib
    - pandas
    - scikit-learn
    - ipykernel
    - kaggle
