name: xray_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - torch
  - pip
  - pip:
    - numpy==1.26.2
    - matplotlib
    - pandas==2.1.4
    - scikit-learn
    - ipykernel
    - kaggle
